### ISSUE TITLE
Some CSS-fix for Switchers (checkboxs)

### ISSUE THREAD

**Issue by wdmg** [timcreative/get-shit-done-pro#11]
Test your kit in Opera / 9.80 (Windows NT 6.1) Presto / 2.12.388 Version / 12.16 / 1860 and found incorrect display switchers (see screen: http://grab.by/DGAA).

Fixed, I cite the CSS code here: http://jsfiddle.net/wdmg/mpd1f8ke/3/

**Comment by alexandru-paduraru** [comment]
Hi,

Thank you for the information and for the fix, that was quick :-). It will be available in the next update.

All the best,
Alex
