### ISSUE TITLE
Label coloring

### ISSUE THREAD

**Issue by ahoekie** [timcreative/get-shit-done-pro#12]
When using labels inside other tags like Headers or Tables the colors don't work and always fallback to the default grey style. This makes the labels really less useful.

**Comment by ahoekie** [comment]
Same goes for labels inside tables

**Comment by Raducioiu** [comment]
Hi there! We tested this scenario but didn't found any bugs. Can you be more explicit with the cases? I will attach a print screen of a label inside a header that works just fine (the same with the table). Please respond with a print screen as well if you don't find the solution in our example
![label test](https://cloud.githubusercontent.com/assets/3780621/6020258/7afc4c34-abb2-11e4-9977-9e2376c33cdf.jpg)
.

**Comment by ahoekie** [comment]
Hmm this is really strange. I had lot's of issues with this and wrote a lot of css to fix it. However after your feedback I retested and disabled all my custom css and it still worked. Not sure what happened here. Sorry for the inconvenience. I will close the issue and if i experience it again will make sure to have a proper sample.
