### ISSUE TITLE
Modal on Mobile

### ISSUE THREAD

**Issue by thetimmyc** [timcreative/get-shit-done-pro#14]
Hi there, on the smallest bootstrap responsive width (< 768px) the modal dialog does not appear within the viewable window if you are scrolled down on the page.  It comes up too high on the page.  You can confirm this on the demo components page on the Pro package by clicking the "Launch Demo Modal" button when the browser width is mobile-sized.  If there is not an official fix coming soon, I would be happy to accept a JS/CSS patch that I can apply as I've been unable to repair it myself up to this point.

**Comment by alexandru-paduraru** [comment]
Hi,

We checked the modal on this link http://get-shit-done-pro.herokuapp.com/components where it is on the bottom of the page and this is our result:
![img_6066](https://cloud.githubusercontent.com/assets/2517758/6041459/50346030-ac85-11e4-84dd-14b8573d999a.PNG)

Can you please give a link to your website, the device that you tested and the browser? In this way we can simulate your environment.

All the best,
Alex

**Comment by thetimmyc** [comment]
Hey thanks for getting back so quickly.  I do see the same thing you do at that link:

 http://get-shit-done-pro.herokuapp.com/components

And it appears all is well.  However, when I download the actual zip file:

x_get_shit_done_pro_html_1.3.1.zip

unzip it, and open the components.html page in Chrome on a Mac (sized down to simulate mobile width), I see this: 

![screen shot 2015-02-04 at 9 40 45 am](https://cloud.githubusercontent.com/assets/1574285/6042356/f519d352-ac51-11e4-8f49-cf3ab7705692.png)

My website isn't online yet so I can't link to it, but the same thing happens on iPhone there.

It appears that the components page in your live demo is a bit different (e.g., there are three modal examples in yours and only in one the downloadable file).  Is it possible I am downloading an older version?

**Comment by Raducioiu** [comment]
Hello,

You have the latest version but there was a bug on Components page. We are sorry for the inconvenience. There will be an update in the near future with the fix but until then here is the solution:

Move the div that contains the modal outside the div class="wrapper" just above /body just like in this screenshot:
![modal-bug](https://cloud.githubusercontent.com/assets/3780621/6044003/2251b334-ac99-11e4-8619-0a6e0b2850e8.jpg)

**Comment by thetimmyc** [comment]
There we go!  Perfect.  Thanks very much for your help.
