### ISSUE TITLE
select picklist within a modal is not rendered

### ISSUE THREAD

**Issue by egroenen** [timcreative/get-shit-done-pro#17]
Never mind - the problem was in the documentation (or lack thereof) it wasn't clear to me that I had to include bootstrap-select.js. After investigating that became clear. I think that any functionality that requires a hs other than get-shit-done.js should be documented along with the component in components.html.

**Comment by egroenen** [comment]
Looks like it is a common issue between bootstrap-select and bootstrap-modal.

A solution is in: http://stackoverflow.com/questions/27381311/bootstrap-select-inside-modal-dont-show-properly

Fiddle: http://jsfiddle.net/mijopabe/gj9axc18/5/

Note the Javascript that refreshes the bootstrap-select when the modal is shown. 

GSDK needs something like this call to refresh for this to work.

**Comment by alexandru-paduraru** [comment]
Hi Edward, 

Thank you for the suggestions, we always want to improve the kit, so we will have a better documentation based on the feedback.

All the best,
Alex
