### ISSUE TITLE
Disabling button with mouse over it makes the text blend in with background

### ISSUE THREAD

**Issue by tomgeek** [timcreative/get-shit-done-pro#19]
Hi, 
default style
![normal-button](https://cloud.githubusercontent.com/assets/3134590/7046936/6f3887d0-de09-11e4-9835-b6bb3a40f947.png)
Disabled button with mouse over it
![hover-disabled-button](https://cloud.githubusercontent.com/assets/3134590/7046944/7aeb35d2-de09-11e4-9025-8ffa86dfbb6b.png)

Seems like extra background is inherited from https://github.com/twbs/bootstrap/blob/v3.3.0/less/mixins/buttons.less#L29

I got around it by adding the same to your buttons.less mixin.

**Comment by alexandru-paduraru** [comment]
Thank you for the issue and also for the quick fix. We added in the kit, it will be live soon.
