### ISSUE TITLE
How can I programmatically get the value of a styled Checkbox?

### ISSUE THREAD

**Issue by areindl** [timcreative/get-shit-done-pro#20]
Hi!

I have some issues with the checkbox.js

I am using AngularJS in my App and I cannot retrieve the value of the Checkbox. Do you have a hint on how to grab the value of this input field?

Thanks!

Best,
Anton

**Comment by alexandru-paduraru** [comment]
Hi,

Check this link and let us know how the things are going: http://stackoverflow.com/questions/2834350/get-checkbox-value-in-jquery

**Comment by areindl** [comment]
Thank you. It simply worked with $("#IDofInput").is(':checked');
