### ISSUE TITLE
Minor Styling Bug: Issue with Input Groups

### ISSUE THREAD

**Issue by areindl** [timcreative/get-shit-done-pro#22]
Hi,

I created a form with a input group and noticed incomplete styling for this type of input box.

Here are some screenshots:

![Normal State](http://s27.postimg.org/yvwtebdyr/Bildschirmfoto_2015_06_03_um_09_06_12.png)

![Hover State](http://s27.postimg.org/pa38y0msz/Bildschirmfoto_2015_06_03_um_09_06_26.png)

I added a light grey background behind the icons. Without that it even looked worse.

Although the screenshots doesn't look so bad, I reality and next to the other input fields, this styling looks faulty.

Best Regards,
Anton

**Comment by alexandru-paduraru** [comment]
Hi,

Thank you for pointing out. Can you please download the latest version from http://www.creative-tim.com/product/get-shit-done-pro. We made an update on 26.05.2015 for the input-group-addon.

Let me know if that worked for you.

Best,
Alex

**Comment by areindl** [comment]
Hi Alex.

Thanks for the quick reply.

I downloaded the new version and  updated the less files. However it did not change.

I am wondering what I did wrong right now and still investigating.

Best regards,
Anton

**Comment by alexandru-paduraru** [comment]
How are the things going? Can you send me the file that you have so I can manually check your example?

**Comment by areindl** [comment]
Hi! What kind of file do you need? The HTML Markup?

**Comment by alexandru-paduraru** [comment]
Yes :-)

**Comment by areindl** [comment]
OK! Attached you find HTML and CSS.

Input Groups are used for Inputs #total_days and #total_value


Thank you for the help.
Anton

**Comment by alexandru-paduraru** [comment]
Sorry but I cannot see the attachments, can you send them at axelut@me.com please?

**Comment by alexandru-paduraru** [comment]
Fixed within the email that I sent you.

Thank you again for the identification of the bug.
