### ISSUE TITLE
I think GSDK should assist in auto-closing notifications

### ISSUE THREAD

**Issue by egroenen** [timcreative/get-shit-done-pro#23]
Hi,

I had to add the following to auto-close notifications, I think they work better like this. I think GSDK should provide a mechanism to do this for you.

```
        $(document).ready(function() {
            window.setTimeout(function() {
                var fade = { opacity: 0, transition: 'opacity 0.5s' };
                $(".alert").css(fade).slideUp(500, function(){
                    $(this).remove(); 
                });
            }, 5000);
        });
```

**Comment by alexandru-paduraru** [comment]
Hi,

That is a great improvement. Thank you!

We will add it also in kit and will be available if you add a class on the notification like "notification-auto-close" so in this way, the users who wants to keep the notification will not be forced to hide it.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Hi, 

Tha auto-closing feature was added in v1.4.2 you can use the class "alert-auto-close" and the alert will be closing in 5 seconds.

Best,
Alex
