### ISSUE TITLE
bootstrap-datepicker throw errors

### ISSUE THREAD

**Issue by BenevidesLecontes** [timcreative/get-shit-done-pro#24]
When i'm using datepicker, i get errors like this:
bootstrap-datepicker.js:410 Uncaught TypeError: Cannot read property 'split' of undefined
bootstrap-datepicker.js:129 Uncaught TypeError: Cannot read property 'hide' of undefined

**Comment by alexandru-paduraru** [comment]
Thank you for being our customer. Don't know how we missed this issue... Please make sure all the javascript files are included. We checked the original archive and we couldn't find the error that you point.

Best,
Alex
