### ISSUE TITLE
[Feature Request] Auto suggestion for tags input

### ISSUE THREAD

**Issue by AzrielOmega** [timcreative/get-shit-done-pro#27]
Can you consider to make a user's config preset of choices for tags input ? I'll very appreciate and grateful to use that.

P/S: I'm using this for autocomplete tags
```
https://github.com/aehlke/tag-it
```

**Comment by alexandru-paduraru** [comment]
Thank you for the suggestion, it was added in v1.4.3, you can download it on your dashboard in creative-tim.com

Best,
Alex
