### ISSUE TITLE
Alignment issues in Safari viewing components.html in GSDK 1.4

### ISSUE THREAD

**Issue by talkingpixels** [timcreative/get-shit-done-pro#29]
A couple of alignment issues spotted in Safari 9.0 (11601.1.56) ... 

<img width="391" alt="screen shot 2015-11-17 at 22 29 34" src="https://cloud.githubusercontent.com/assets/104806/11226935/0446cd84-8d7b-11e5-9f09-13d70975c2f4.png">

<img width="328" alt="screen shot 2015-11-17 at 22 30 00" src="https://cloud.githubusercontent.com/assets/104806/11226936/04489952-8d7b-11e5-8224-28fdf9521f59.png">

**Comment by AzrielOmega** [comment]
_**Error with input align:**_
Problem: glyphicon margin-top;
Solution: 
Solution 1. Using input_group_addon and font-awesome like input group addon example.
Solution 2. in _**gsdk.css**_, replace

**.form-control + .form-control-feedback** {
    border-radius: 6px;
    font-size: 14px;
    _**margin-top: -7px;**_
    position: absolute;
    right: 10px;
    top: 50%;
    vertical-align: middle;
}

with 

**.form-control + .form-control-feedback** {
    border-radius: 6px;
    font-size: 14px;
    _**margin-top: -16px;**_
    position: absolute;
    right: 10px;
    top: 50%;
    vertical-align: middle;
}

_**Error with button purchase:**_

It's a table with overflow scrolling, just scroll it.

**Comment by AzrielOmega** [comment]
P.S: using table for mobile and tablet responsive structure is a very bad idea.

**Comment by talkingpixels** [comment]
Thanks Azriel for speedy reply! It's something I spotted in the example file that comes in the GTDK download, so thought I'd report.

**Comment by AzrielOmega** [comment]
I'm purchased GSDK too, and really like it. Just want to share a quick fix if you need it in hurry.

**Comment by talkingpixels** [comment]
Yeah, it's very cool. Many thanks :)

**Comment by alexandru-paduraru** [comment]
@AzrielOmega @talkingpixels thank you for the information and also for the suggestions for fixing it, you're awesome :+1: I saw that you said using the responsive structure for mobile/tablet is a bad idea. Do you have any suggestions on how we can fix this for a better experience in mobile/tablet? 

Keep in touch,
Alex

**Comment by AzrielOmega** [comment]
I said using TABLE in mobile/tablet is a bad idea and I tried to avoid using table if not necessary. But if I have to use it, I usually have to write two table structures, one for large-medium screen and one for small-extra small. And it is, sometimes, very tiresome.

**Comment by juliyvchirkov** [comment]
greetings

https://github.com/timcreative/get-shit-done-pro/issues/30

here you can find another way to fix this alignment issue

seems this way will be more simple and correct, 'cause it used by «Get shit done PRO» developers in other examples

**Comment by alexandru-paduraru** [comment]
Fixed in v1.4.2
