### ISSUE TITLE
claret disappears on iOS 9 iPhone

### ISSUE THREAD

**Issue by vickituch** [timcreative/get-shit-done-pro#32]
claret disappears for drop down menus on iOS 9.2 iPhone

**Comment by alexandru-paduraru** [comment]
@vickituch we just saw the issue here, I know we fixed this, over the Skype call with you, some days ago so I will close it here. The update for all the users will be added in the next release of the kit. 

Best,
Alex

**Comment by vickituch** [comment]
Great, thanks for fixing!

Regards Vicki
> On 22 Jan 2016, at 10:50, Alex Paduraru <notifications@github.com> wrote:
> 
> @vickituch <https://github.com/vickituch> we just saw the issue here, I know we fixed this, over the Skype call with you, some days ago so I will close it here. The update for all the users will be added in the next release of the kit.
> 
> Best,
> Alex
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/timcreative/get-shit-done-pro/issues/32#issuecomment-173877259>.
> 


Vicki Bellamy
Tuch Design – brand design and marketing 
m 07940 370612 <tel:07940 370612>    t 020 8758 1758 <tel:020 8758 1758> 
skype vickibellamy <skype:vickibellamy?add>   vicki@tuchdesign.com  <mailto:vicki@tuchdesign.com>
www.tuchdesign.com <http://www.tuchdesign.com/>
 <https://www.facebook.com/Tuch.Design.Limited> 
 <https://twitter.com/tuch_design> 
 <https://www.linkedin.com/in/tuchdesign> 
 <https://plus.google.com/u/0/b/117439928934373012808/117439928934373012808/about> 
Read email disclaimer  <http://www.tuchdesign.com/email.html>
Tuch Design Limited is a company registered in England and Wales company no: 2319426 <applewebdata://98C64454-229C-453D-8DCC-705C3CE1E997>
