### ISSUE TITLE
Tags Input Autocomplete

### ISSUE THREAD

**Issue by jcperez2405** [timcreative/get-shit-done-pro#33]
How you can configure the Tags Input autocomplete option?

On "jQuery Tags Input Plugin" Documentation you can use:
jQuery('#tags').tagsInput({
  autocomplete_url:'http://myserver.com/api/autocomplete'
});

But this don't work on yours.

**Comment by alexandru-paduraru** [comment]
@jcperez2405 Thank you for using our product. We checked and you're right, the autocomplete feature of the Tags is not working. We will check again the difference between the files that are on the jQuery Tags plugin on github and what we have inside our kit.

We will come with a solution for you this week, Tue/Wed when we get back to the office.

Keep in touch,
Alex

**Comment by jcperez2405** [comment]
Great! I'll be waiting for this fix...

**Comment by AzrielOmega** [comment]
I second that. This feature is pretty useful for tagging management

**Comment by AzrielOmega** [comment]
And if you seek alternative plugin for tag in GSDK, please check out this plugin. It pretty solid and good document.

**Comment by AzrielOmega** [comment]
http://aehlke.github.io/tag-it/

**Comment by alexandru-paduraru** [comment]
@jcperez2405 sorry for the late response, we started to integrate the autocomplete and then we found other items which had conflicts with the jQuery UI, so fixing everything took a little bit longer than we expected. We integrated the Autcomplete and you can test it here: http://gsdk.creative-tim.com/components in the Tags area. The autcomplete feature is available in the archive V1.4.3 from your dashboard inside creative-tim.com

Please check it and let us know if everything is ok.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
@AzrielOmega thank you for the suggestion, but we found a nice way to make the default tags working. Please check them here http://gsdk.creative-tim.com/components in the tags area. If the autocomplete dropdown is not looking very good, please do a cmd + R refresh or clear the cache, so you will get the latest CSS. 

Best, 
Alex
