### ISSUE TITLE
Navbar break into 2-3 lines when it too long.

### ISSUE THREAD

**Issue by AzrielOmega** [timcreative/get-shit-done-pro#34]
Currently, navbar will fully show on sm-md-lg screen and hambuger button on xs screen. But if I have a little long left side of navbar, so the right side will fall down and drop outside of navigation bar. So please tell me how can I tweak the navbar css to show fully on md-lg sreen and hambuger button on xs-sm screen ?

**Comment by alexandru-paduraru** [comment]
Hi @AzrielOmega can you please give us a link to your project? We want to see if we have any alternative because changing the responsive to act different on a bigger screen than what is is set now would take some time to be implemented. There are dependencies between the javascript that is activating the side navigation and the CSS style that was written in the original Bootstrap. If we cannot give you an alternative, we will see what we can do to change the responsive triggers for md-lg screens.

Keep in touch,
Alex

**Comment by AzrielOmega** [comment]
Sorry for the late response. My project is still on localhost and I haven't had domain to upload yet. But this problem in Bootstrap 3 is mentioned before and somebody had a solution. I tried it but it's not compatible with GSDK css. Here is the similar case on native Bootstrap 3:
http://stackoverflow.com/questions/22228239/bootstrap-navbar-static-top-menu-breaks-on-two-lines

**Comment by alexandru-paduraru** [comment]
Hi @AzrielOmega, we've checked the solution from StackOverflow and then we came with some adjustments for the kit. So please go to:

1. to the assets/js/get-shit-done.js and on line 15 change the 768 to 991, then on line 106 change the 768 to 991. In this way we will trigger the burger menu on the 991 breakpoint.
2. Download the SASS compiler Koala, or any other SASS compiler, so we will make adjustments in the SASS files
3. go to assets/sass/gsdk/_responsive.scss on line 2 and change this:

    @media (min-width: 768px){
with this:

    @media (min-width: 992px){ 

then on line 96 change this:

    @media (max-width: 767px){

with this:

    @media (max-width: 991px){

4. please go in the same _responsive file to the line 93 and add this code:

    .navbar-toggle {
        display: none;
    }
    .navbar-header{
        float: none;
    }

then please go to the line 104 or somewhere inside the @media(max-width:991px) and add this code:

.navbar-toggle{
        display: block;
    }

    .navbar-transparent{
        padding-top: 15px;
        background-color: rgba(0, 0, 0, 0.45);
    }

Then we have the breakpoint to 991px and it should not go to 2 lines. Please let me know if that is ok.

We will include this fix in a future update, I think it is better to have the break point to 991px

Best,
Alex

**Comment by AzrielOmega** [comment]
Thank you @alexandru-paduraru. It work like a charm. I hope in the future bootstrap can make a navbar like xenForo website software. It just auto collapse overflow navbar one-by-one. Anyway, thank you for your hard working and be very supportive.

**Comment by alexandru-paduraru** [comment]
@AzrielOmega you're welcome! :-)
