### ISSUE TITLE
Navbar with Icons in Responsive Mode

### ISSUE THREAD

**Issue by mentrac** [timcreative/get-shit-done-pro#38]
Hi,

I'am using the GSDK to my web app company without problems. But, When I try use NavBar with Icons and label class for notifications, all text and icons stayed misaligned. When I go to Responsive Mode, the Icons stay so small and text misaligned too.

The live demo of our project: http://dev.mentrac.com/index.php

We tries fix the align with some css classes, but, not success. 

How I do to fix it and leave Responsive Icons align with text box. An pretty presentation. 

Hugs,
Mentrac DEV

**Comment by AzrielOmega** [comment]
You just fixed it? I tried but everything work OK now.

**Comment by mentrac** [comment]
Hi Azriel,

We change icons on Dropdown menu by FontsAwesome and its ok! 

But, The SE 7 Stroke icons set on the top (navbar) with "navbar navbar-icons navbar-ct-blue navbar-fixed-top" classes in Responsive mode stay stranger. We try align the icon and text ... but not yet.

Example:

Current, in responsive mode:

[ ICON ]
[ TEXT LINK ] [CARRET]

Future:

[ ICON ] [ TEXT LINK ] [CARRET]

In our perfect world, should be:

[ ICON ] [ TEXT LINK ] [CARRET] [NOTIFICATION ICON]

Take a look for notification icon in responsive mode, see on top - right screen. 

Note:

May be difficult to see the HTML code because all HTML tags is embedded in PHP Classes, if necessary, we put the full code or access from secure account ftp.

Thanks for your support until the moment.

**Comment by AzrielOmega** [comment]
Here the quick solution for pe icons menu only:

For each p tag in menu, add a style:
`.nav .dropdown > p {display: inline-block; margin-left: 10px;}`

and in **basico.css** change

`.label_menu {
    background-color: red;
    color: white;
    border: none;
    position: absolute;
    right: 10px;
    top: 0px;
    font-size: 10px;
    text-shadow: none;
}`
with
`.label_menu {
    background-color: red;
    color: white;
    border: none;
    position: absolute;
    left: 15px;
    bottom: 0px;
    font-size: 10px;
    text-shadow: none;
}`

**Comment by mentrac** [comment]
Azriel, Perfect!

The last doubt is:

How I align the SE 7 Stroke icon side-by-side with text link when open in Responsive mode?

Current, the icon is very small and on the top of text (it seems stranger) when you use the app from iphone.

The label problems was fixed. Many thanks.

**Comment by AzrielOmega** [comment]
**First**, change size of `<i>`tag and make it absolute:

`.nav .dropdown > a > i {font-size:30px; position:absolute}`

**Second**, stretch the notification equal to the icon, just add left:0; right:0 to css

`.label_menu {
    background-color: red;
    color: white;
    border: none;
    position: absolute;
    left: 0;
    right: 0;
    bottom: -20px;
    font-size: 10px;
    text-shadow: none;
}`

**Third**, make `<p>` tag width equal to menu minor the width of icon:

`.nav .dropdown > p {display: inline-block; margin: 0 0 0 35px;}`

**Comment by AzrielOmega** [comment]
Here the result: http://i.imgur.com/MYsXsbs.png

**Comment by mentrac** [comment]
Your result was perfect. 

I did the changes, but, I <p> tag align left screen... I dont know if safari is rendering correctly.

**Comment by mentrac** [comment]
http://imgur.com/vyNdS8a

**Comment by AzrielOmega** [comment]
Forget the previous attempt. Let try this:

`
.nav li > a > i {
    font-size:30px;
    position:absolute;
}

.label_menu {
    background-color: red;
    color: white;
    border: none;
    position: absolute;
    top: 0;
    right: 0px;
    font-size: 10px;
    text-shadow: none;
    float: right;
}

.nav li > a > p {
    display: inline-block;
    margin: 3px 0 0 35px;
}
`

To make
[ ICON ] [ TEXT LINK ] [CARRET] [NOTIFICATION ICON]
is quite hard when Notification Icon is a `<span>` inside icon `<i>`.

**Comment by AzrielOmega** [comment]
Result: http://imgur.com/a/i7lf3

**Comment by mentrac** [comment]
Azriel.... now its perfect. Here work well too. 

But... dropdown items overrride the changes. 

Take a look... 

<img width="230" alt="captura de tela 2016-07-19 as 18 36 29" src="https://cloud.githubusercontent.com/assets/20543964/16967558/e32ef0ce-4ddf-11e6-8e84-743adbed9692.png">

**Comment by mentrac** [comment]
For Mobile... this changes its perfect! Perfect... Perfect...

For desktop, maybe override some css class from GSDK menu.

**Comment by AzrielOmega** [comment]
Nah, you just forget to warp text in `<p>` in child nav...

**Comment by mentrac** [comment]
dam... try `<p>` tag but no better.. 

I try use like it:

`<li><a href="#" style="padding-left: 30px;"><i class="fa fa-home fa-fw" aria-hidden="true" style="font-size: 14px; margin: 3px -20px; 0px 0px;"></i>&nbsp;Conta</a></li>`

seems better in desktop and responsive mode.... just workarround... 

But `<ol>` elements misaligned with nav-brand class. I try fix into margin and padding in dropmenu collapse divs... but stay terrible...

**Comment by AzrielOmega** [comment]
`<li>
    <a href="#">
        <i class="pe-7s-user"></i>
        <p> Account</p>
    </a>
</li>`

**Comment by alexandru-paduraru** [comment]
@mentrac it looks like @AzrielOmega it's right. You need to wrap the text when you use the Stroke icons inside a <p>text here</p> and everything will work fine. Please check the attached image:

<img width="651" alt="screen shot 2016-07-20 at 17 22 06" src="https://cloud.githubusercontent.com/assets/2517758/16989955/cf6998ae-4e9e-11e6-870b-c3da86d9c085.png">

**Comment by mentrac** [comment]
Hi Folks... 

Thanks for support. Menu work well now. I did the changes suggest by Azriel... work fine!
